import enum

class SignalStatus(str, enum.Enum):
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    STORED = "STORED"
    PENDING_INTERPRETATION = "PENDING_INTERPRETATION"
    INTERPRETED = "INTERPRETED"
    INTERPRETATION_FAILED = "INTERPRETATION_FAILED"
    REVIEWED = "REVIEWED"
    CLOSED = "CLOSED"
    ERROR = "ERROR"

class RawWebhookParseStatus(str, enum.Enum):
    RECEIVED = "RECEIVED"
    PARSED = "PARSED"
    INVALID_JSON = "INVALID_JSON"
    SCHEMA_REJECTED = "SCHEMA_REJECTED"
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    SIGNAL_CREATED = "SIGNAL_CREATED"
    ERROR = "ERROR"

class DataSourceQuality(str, enum.Enum):
    SEEDED_DEMO = "SEEDED_DEMO"
    REAL_CAPTURED = "REAL_CAPTURED"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"

class SignalDomain(str, enum.Enum):
    CRYPTO_SPOT = "CRYPTO_SPOT"
    B3_EQUITIES = "B3_EQUITIES"

class MarketSession(str, enum.Enum):
    PRE_MARKET = "PRE_MARKET"
    REGULAR_SESSION = "REGULAR_SESSION"
    CLOSING_PHASE = "CLOSING_PHASE"
    AFTER_MARKET = "AFTER_MARKET"
    OUT_OF_SESSION = "OUT_OF_SESSION"

class InterpretationStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    INVALID_RESPONSE = "INVALID_RESPONSE"

class ThesisCategory(str, enum.Enum):
    TREND_ALIGNED = "TREND_ALIGNED"
    BREAKOUT_CONTEXT = "BREAKOUT_CONTEXT"
    RANGE_CONFLICT = "RANGE_CONFLICT"
    WEAK_SIGNAL = "WEAK_SIGNAL"
    VOLATILITY_WARNING = "VOLATILITY_WARNING"
    AGGRESSIVE_ONLY = "AGGRESSIVE_ONLY"
    CONSERVATIVE_FIT = "CONSERVATIVE_FIT"
    UNCLEAR_CONTEXT = "UNCLEAR_CONTEXT"
